% EXPORTFIG
%
% Files
%   append_pdfs                - Appends/concatenates multiple PDF files
%   copyfig                    - Create a copy of a figure, without changing the figure
%   crop_borders               - Crop the borders of an image or stack of images
%   eps2pdf                    - Convert an eps file to pdf format using ghostscript
%   export_fig                 - Exports figures in a publication-quality format
%   fix_lines                  - Improves the line style of eps files generated by print
%   ghostscript                - Calls a local GhostScript executable with the input command
%   im2gif                     - Convert a multiframe image to an animated GIF file
%   isolate_axes               - Isolate the specified axes in a figure on their own
%   pdf2eps                    - Convert a pdf file to eps format using pdftops
%   pdftops                    - Calls a local pdftops executable with the input command
%   print2array                - Exports a figure to an image array
%   print2eps                  - Prints figures to eps with improved line styles
%   read_write_entire_textfile - Read or write a whole text file to/from memory
%   user_string                - Get/set a user specific string
%   using_hg2                  - Determine if the HG2 graphics engine is used
